### ISSUE TITLE
Poor results on DTU after pulling recent commits.

### ISSUE THREAD

**Issue by HLinChen** [NVlabs/neuralangelo#101]
I have trained on DTU before and the results look good. However, after git pull recent commits, I train on DTU again and the results are poor. Can you help me find the problems?

<img width="1838" alt="image" src="https://github.com/NVlabs/neuralangelo/assets/37725241/6e629263-ef65-468e-85a0-6dd3182c9d08">
<img width="1825" alt="image" src="https://github.com/NVlabs/neuralangelo/assets/37725241/018a59ab-abea-4c77-9691-51d0090201ba">

**Comment by HLinChen** [comment]
Hi @mli0603 

Thanks for your reply. The commit ID is b772282d26f62064401b1f4f0d53eefe908afdb3.

**Comment by mli0603** [comment]
Hi @HLinChen 

There is a bug in data loading in the recent commits. We are fixing this and will update.

**Comment by mli0603** [comment]
Hi @HLinChen 

Can you try the following? We have recently updated the data loading script and thus the `transforms.json` needs to be updated.

```
PATH_TO_DTU=datasets/dtu  # Modify this to be the DTU dataset root directory.
python3 projects/neuralangelo/scripts/convert_dtu_to_json.py --dtu_path ${PATH_TO_DTU}
```

**Comment by HLinChen** [comment]
Thank you very much! The problem has been solved.
