### ISSUE TITLE
run extract_mesh.py falied

### ISSUE THREAD

**Issue by xuduo18311199384** [NVlabs/neuralangelo#105]
![2023-09-05 09-52-12 的屏幕截图](https://github.com/NVlabs/neuralangelo/assets/30895764/4e6e725c-2329-4092-bb48-ffe74fcc2605)
How to deal with it?

**Comment by mli0603** [comment]
Hi @xuduo18311199384 

It looks like you are running an old version of trimesh, which does not have `nondegenerate_faces` functionality. Are you running the docker or a conda env?

**Comment by xuduo18311199384** [comment]
I just build env by "pip install". I confirm there is something wrong with my 'trimesh'. I sovled the problem by Annotating this sentence "mesh.update_faces(mesh.nondegenerate_faces())".

**Comment by mli0603** [comment]
Hi @xuduo18311199384 

Good to know! Closing this now.
