### ISSUE TITLE
cropping/editing pointcloud to remove noise

### ISSUE THREAD

**Issue by Choco83** [NVlabs/neuralangelo#111]
Is there a way to crop/edit pointcloud more finely. With custom videos that I create I am getting a lot of noise near actual object which is not possible to remove using BlenderTool mentioned in data preprocessing guide, also to my understanding it only updates sphere radius in transforms.json and not actually crop the pointcloud.

Is there any way or suggestion how to tackle this problem?

**Comment by chenhsuanlin** [comment]
Hi @Choco83, the point clouds are not actually used in Neuralangelo -- only the cameras and the bounding sphere matters. As long as you are able to identify the region of your interest for reconstruction, you should be fine.
