### ISSUE TITLE
Error occured when training on the synthetic data that not from nerf

### ISSUE THREAD

**Issue by Then0109** [NVlabs/neuralangelo#126]
Dear author,
Thanks for releasing the codes.
After training the model on real scene data,i am trying to train the synthetic data.
And i choose a synthetic dataset from other model. However,i don't know if it's the data doesn't fit the model that affects the results.

If i just input the origin rgba images into the model,then the config generation process would be interrupted by the 'bgcolor' error.

If i change the rgba images to rgb images and input the rgb images,the process would successfully finish,while the result is very bad.

In fact,the output rgb image synthesis is white without any information.Here are some of the dataset information and results.
Could you please help me with my synthetic data test?
Appreciate it very much.

dataset from ref-nerf  (train on the linux system):
![屏幕截图 2023-09-25 175412](https://github.com/NVlabs/neuralangelo/assets/119100650/f8ae8a18-e882-4e12-8d9b-4206862e131b)
![屏幕截图 2023-09-25 175436](https://github.com/NVlabs/neuralangelo/assets/119100650/5471bcaa-9f52-4bc7-b639-b2d6aaa2ada1)![r_0](https://github.com/NVlabs/neuralangelo/assets/119100650/0cb8a3aa-2231-4968-8d0d-d363970d1559)
results:
![屏幕截图 2023-09-25 175326](https://github.com/NVlabs/neuralangelo/assets/119100650/59e0a57d-f016-414a-9743-3227c356818b)

**Comment by mli0603** [comment]
Hi @Then0109 

The normal/depth/opacity suggests that the poses of the camera are likely wrong. Usually, for object-centric scenes, you would expect a sphere in the middle of the image during the start of optimization.

**Comment by Then0109** [comment]
Thank you for the tip for checking out the camera poses.
Actually, I use the colmap to directly predict the poses of camera.
I check out the poses of camera with ipynb then,it looks correct anyway.
![image](https://github.com/NVlabs/neuralangelo/assets/119100650/04060020-0e7f-4e9c-bea1-faf647d89836)
I don't know if it's the **'RGBA'** data that is not suitable the 'right' llff type data input deman,because when i changed the data type to 'nerf_blender',then the error that the AttrDict object has no attribute  'bgcolor' occured. 
Also,i noticed that the data type in the 'lego' data  config is nerf_llff, while it's not working anyway if i convert the **RGBA** data into video and input the model.

**Comment by mli0603** [comment]
I see. Good to know you have resolved the problem by using the poses from COLMAP. I think there is a convention difference between LLFF and COLMAP, which may have caused your previous issue. I will close this for now as things are working.
