### ISSUE TITLE
Error when exracting Mesh

### ISSUE THREAD

**Issue by ChengWan9** [NVlabs/neuralangelo#141]
when I ran my case,the ckpt seems ok(4.1 G),but when extracting mesh, it shows as following:
<img width="1081" alt="66da8c8c62037c103f85bb56225c2e2" src="https://github.com/NVlabs/neuralangelo/assets/143673887/96586408-8f7a-4726-8454-bdc05a4e74ce">
i had used the latest version of neuralangelo,and a week ago,it rans correctly on other cases can u help me?

**Comment by Ryan-ZL-Lin** [comment]
I encountered the same issue, and I solved this problem by removing the `--keep_lcc` parameter from the surface extraction command.

**Comment by ChengWan9** [comment]
> I encountered the same issue, and I solved this problem by removing the `--keep_lcc` parameter from the surface extraction command.

thank you a lot!
I will try it!
