### ISSUE TITLE
ModuleNotFoundError: No module named 'third_party.colmap'

### ISSUE THREAD

**Issue by thevaibhavkute** [NVlabs/neuralangelo#147]
![image](https://github.com/NVlabs/neuralangelo/assets/68586341/8a803826-edc1-4e63-ad94-1aeffc6d7767)

getting the below error while running the above script... I have not made any changes still getting this error.
After that I have tried to edit that file inside but still getting this error

Error:
```
.
.
.
Undistorting image [97/100]
Undistorting image [98/100]
Undistorting image [99/100]
Undistorting image [100/100]
Writing reconstruction...
Writing configuration...
Writing scripts...
Elapsed time: 0.218 [minutes]
Traceback (most recent call last):
  File "/content/neuralangelo/projects/neuralangelo/scripts/convert_data_to_json.py", line 24, in <module>
    from third_party.colmap.scripts.python.read_write_model import read_model, qvec2rotmat  # NOQA
ModuleNotFoundError: No module named 'third_party.colmap'
Config generated to file: /content/neuralangelo/projects/neuralangelo/configs/custom/lego.yaml
----------------------------------------
Number of registered images: 100
```

**Comment by NagaPadma** [comment]
I do have the same error. I have changed the code and tried yet facing the same error.

**Comment by shayikhhossain** [comment]
I'm facing the same issue: **_No module named 'third_party.colmap'_**

Someone please help!

**Comment by guomc9** [comment]
Errors may occur when coding "from third_party.xxx import xxx".

1. Find 
```
/content/neuralangelo/projects/neuralangelo/scripts/convert_data_to_json.py
```
2. Comment
```
dir_path = Path(os.path.dirname(os.path.realpath(__file__))).parents[2]
sys.path.append(dir_path.__str__())
```
3. Add codes after comments above.
``` 
sys.path.append('/content/neuralangelo/third_party')
``` 

4. Find code after that:
```
from third_party.colmap.scripts.python.read_write_model import read_model, qvec2rotmat
``` 
5. then fix to:
``` 
from colmap.scripts.python.read_write_model import read_model, qvec2rotmat
```
![屏幕截图 2023-11-15 125554](https://github.com/NVlabs/neuralangelo/assets/134785997/14eb0f8a-5ec4-4e36-95ea-8ea88bf95f77)

**Comment by NagaPadma** [comment]
> Errors may occur when coding "from third_party.xxx import xxx".
> 
> 1. Find
> 
> ```
> /content/neuralangelo/projects/neuralangelo/scripts/convert_data_to_json.py
> ```
> 
> 2. Comment
> 
> ```
> dir_path = Path(os.path.dirname(os.path.realpath(__file__))).parents[2]
> sys.path.append(dir_path.__str__())
> ```
> 
> 3. Add codes after comments above.
> 
> ```
> sys.path.append('/content/neuralangelo/third_party')
> ```
> 
> 4. Find code after that:
> 
> ```
> from third_party.colmap.scripts.python.read_write_model import read_model, qvec2rotmat
> ```
> 
> 5. then fix to:
> 
> ```
> from colmap.scripts.python.read_write_model import read_model, qvec2rotmat
> ```
> 
> ![屏幕截图 2023-11-15 125554](https://user-images.githubusercontent.com/134785997/283008375-14eb0f8a-5ec4-4e36-95ea-8ea88bf95f77.png)

thank you so much :) . it worked 👍.

**Comment by thevaibhavkute** [comment]
> Errors may occur when coding "from third_party.xxx import xxx".
> 
> 1. Find
> 
> ```
> /content/neuralangelo/projects/neuralangelo/scripts/convert_data_to_json.py
> ```
> 
> 2. Comment
> 
> ```
> dir_path = Path(os.path.dirname(os.path.realpath(__file__))).parents[2]
> sys.path.append(dir_path.__str__())
> ```
> 
> 3. Add codes after comments above.
> 
> ```
> sys.path.append('/content/neuralangelo/third_party')
> ```
> 
> 4. Find code after that:
> 
> ```
> from third_party.colmap.scripts.python.read_write_model import read_model, qvec2rotmat
> ```
> 
> 5. then fix to:
> 
> ```
> from colmap.scripts.python.read_write_model import read_model, qvec2rotmat
> ```
> 
> ![屏幕截图 2023-11-15 125554](https://user-images.githubusercontent.com/134785997/283008375-14eb0f8a-5ec4-4e36-95ea-8ea88bf95f77.png)

Thanks a lot!!

**Comment by EntityinArray** [comment]
> Errors may occur when coding "from third_party.xxx import xxx".
> 
> 1. Find
> 
> ```
> /content/neuralangelo/projects/neuralangelo/scripts/convert_data_to_json.py
> ```
> 
> 2. Comment
> 
> ```
> dir_path = Path(os.path.dirname(os.path.realpath(__file__))).parents[2]
> sys.path.append(dir_path.__str__())
> ```
> 
> 3. Add codes after comments above.
> 
> ```
> sys.path.append('/content/neuralangelo/third_party')
> ```
> 
> 4. Find code after that:
> 
> ```
> from third_party.colmap.scripts.python.read_write_model import read_model, qvec2rotmat
> ```
> 
> 5. then fix to:
> 
> ```
> from colmap.scripts.python.read_write_model import read_model, qvec2rotmat
> ```
> 
> ![屏幕截图 2023-11-15 125554](https://user-images.githubusercontent.com/134785997/283008375-14eb0f8a-5ec4-4e36-95ea-8ea88bf95f77.png)

is this fix making its way into the repo?

**Comment by thevaibhavkute** [comment]
> > Errors may occur when coding "from third_party.xxx import xxx".
> > 
> > 1. Find
> > 
> > ```
> > /content/neuralangelo/projects/neuralangelo/scripts/convert_data_to_json.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Comment
> > 
> > ```
> > dir_path = Path(os.path.dirname(os.path.realpath(__file__))).parents[2]
> > sys.path.append(dir_path.__str__())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. Add codes after comments above.
> > 
> > ```
> > sys.path.append('/content/neuralangelo/third_party')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 4. Find code after that:
> > 
> > ```
> > from third_party.colmap.scripts.python.read_write_model import read_model, qvec2rotmat
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 5. then fix to:
> > 
> > ```
> > from colmap.scripts.python.read_write_model import read_model, qvec2rotmat
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![屏幕截图 2023-11-15 125554](https://user-images.githubusercontent.com/134785997/283008375-14eb0f8a-5ec4-4e36-95ea-8ea88bf95f77.png)
> 
> is this fix making its way into the repo?
while running this:
![image](https://github.com/NVlabs/neuralangelo/assets/68586341/2991c7ff-e6b7-487f-97b5-be2a783bc762)
make there this change:
`from neuralangelo.third_party.colmap.scripts.python.read_write_model import read_model`
