### ISSUE TITLE
Does a different object require retraining the model?

### ISSUE THREAD

**Issue by zhj1013** [NVlabs/neuralangelo#156]
Same as the title. I have trained Lego and saved the checkpoint. If I want to perform 3D reconstruction on another object, do I need to retrain the model?

**Comment by Bombaninha** [comment]
Yes, that's the idea of using NeRFs. Every single 3D reconstruction object requires a training step.

**Comment by zhj1013** [comment]
> Yes, that's the idea of using NeRFs. Every single 3D reconstruction object requires a training step.

Thank you for your reply. I got it.
