### ISSUE TITLE
how to properly shoot a video for COLMAP pose extraction?

### ISSUE THREAD

**Issue by zhj1013** [NVlabs/neuralangelo#157]
I would like to know if anyone can guide me on how to properly shoot a video for COLMAP pose extraction? The results from my attempt using a smartphone to film around an object weren't good. I also encountered several issues. For instance, during the colmap image_undistorter phase, the images were cropped and became incomplete. Additionally, when viewing the camera trajectory in visualize_colmap.ipynb, there were problems. Can anyone help me with this?

**Comment by Bombaninha** [comment]
The recommendations made by COLMAP staff are as follows:

> If you have control over the picture capture process, please follow these guidelines for optimal reconstruction results:
> - Capture images with good texture. Avoid completely texture-less images (e.g., a white wall or empty desk). If the scene does not contain enough texture itself, you could place additional background objects, such as posters, etc.
> - Capture images at similar lighting conditions. Avoid high dynamic range scenes (e.g., pictures against the sun with shadows or pictures through doors/windows). Avoid specularities on shiny surfaces.
> - Capture images with high visual overlap. Make sure that each object is seen in at least 3 images – the more images the better.
> - Capture images from different viewpoints. Do not take images from the same location by only rotating the camera, e.g., take a few steps after each shot. At the same time, try to have enough images from a relatively similar viewpoint. Note that more images is not necessarily better and might lead to a slow reconstruction process. If you use a video as input, consider down-sampling the frame rate.

**Comment by zhj1013** [comment]
> The recommendations made by COLMAP staff are as follows:
> 
> > If you have control over the picture capture process, please follow these guidelines for optimal reconstruction results:
> > 
> > * Capture images with good texture. Avoid completely texture-less images (e.g., a white wall or empty desk). If the scene does not contain enough texture itself, you could place additional background objects, such as posters, etc.
> > * Capture images at similar lighting conditions. Avoid high dynamic range scenes (e.g., pictures against the sun with shadows or pictures through doors/windows). Avoid specularities on shiny surfaces.
> > * Capture images with high visual overlap. Make sure that each object is seen in at least 3 images – the more images the better.
> > * Capture images from different viewpoints. Do not take images from the same location by only rotating the camera, e.g., take a few steps after each shot. At the same time, try to have enough images from a relatively similar viewpoint. Note that more images is not necessarily better and might lead to a slow reconstruction process. If you use a video as input, consider down-sampling the frame rate.

So kind of you! Thank you for your reply.
