### ISSUE TITLE
No Metrics such as Test Accuracy  When I use wandb.

### ISSUE THREAD

**Issue by meijinsiwuyu** [NVlabs/neuralangelo#173]
I wonder why there are no metrics like accuracy when using wandb, so when should I decide to stop training?
I Suppose that Input videos should be taken by drones or cameras with a PT-head，is that corrcet？

**Comment by mli0603** [comment]
Hi @meijinsiwuyu, 
- we optimize a scene using a fixed duration instead of tracked metrics. 
- the input videos do not have to come from a camera with panning and tilting functionalities.

I hope this helps!
