### ISSUE TITLE
Error : Failed building wheel for tinycudann

### ISSUE THREAD

**Issue by MicKkmack** [NVlabs/neuralangelo#176]
![image](https://github.com/NVlabs/neuralangelo/assets/105160039/66c967c4-64f9-43bd-917f-837881c85d90)

Im running into an error when running the command pip install -r requirements.txt , I noticed it says this in the error messages :      " The detected CUDA version (11.7) mismatches the version that was used to compile
      PyTorch (12.0). Please make sure to use the same CUDA versions."

But I'm unsure how to fix it, or why I would be getting this error when using the requirements.txt that comes with the repo. Anyone able to help?

**Comment by MicKkmack** [comment]
fixed : 

pip uninstall torch torchaudio torchvision -y
conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia
Running these cmds should do the trick

**Comment by sean1832** [comment]
This is super helpful, I am stuck with the same issue and it solved like magic.

**Comment by weihan1** [comment]
@MicKkmack I tried your fix, but got this issue:

LibMambaUnsatisfiableError: Encountered problems while solving:
  - cannot install both pin-1-1 and pin-1-1

Could not solve for environment specs
The following packages are incompatible
└─ pin-1 is installable with the potential options
   ├─ pin-1 1, which can be installed;
   └─ pin-1 1 conflicts with any installable versions previously reported.
   
   
   Have you encountered this issue before? If so, how did you resolve it?

**Comment by MicKkmack** [comment]
> @MicKkmack I tried your fix, but got this issue:
> 
> LibMambaUnsatisfiableError: Encountered problems while solving:
> 
> * cannot install both pin-1-1 and pin-1-1
> 
> Could not solve for environment specs The following packages are incompatible └─ pin-1 is installable with the potential options ├─ pin-1 1, which can be installed; └─ pin-1 1 conflicts with any installable versions previously reported.
> 
> Have you encountered this issue before? If so, how did you resolve it?

Pins is meta data for packages, so maybe your trying to download a package your already have? (Would explain the 1 - 1 ) Not 100% sure as I've not had that error before. If you pop a screenshot over, I'm currently re-installing Neuralangelo , so I can see if I get the same error.

**Comment by weihan1** [comment]
![Screenshot 2024-02-20 at 2 01 38 PM](https://github.com/NVlabs/neuralangelo/assets/78453818/9600d284-5bfc-4ef8-8057-c303de70319d)

Thanks for your response, this step occurred when I tried reinstalling pytorch via
`conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia`
