### ISSUE TITLE
normal epsilon size is smaller than the cell size.

### ISSUE THREAD

**Issue by K-nowing** [NVlabs/neuralangelo#180]
In this [function](https://github.com/NVlabs/neuralangelo/blob/94390b64683c067c620d9e075224ccfe582647d0/projects/neuralangelo/utils/modules.py#L102), the normal_eps is initially set based on the cell size. However, its value is normalized in the following [line](https://github.com/NVlabs/neuralangelo/blob/94390b64683c067c620d9e075224ccfe582647d0/projects/neuralangelo/utils/modules.py#L83) by the bound size. As a result, normal_eps becomes (bound_size * 2) times smaller than the cell size.

am I missing something?

**Comment by mli0603** [comment]
Hi @K-nowing 

The resolutions of the hash encodings are always defined within the bounded regions, so is the `normal_eps`. The [line](https://github.com/NVlabs/neuralangelo/blob/94390b64683c067c620d9e075224ccfe582647d0/projects/neuralangelo/utils/modules.py#L83) you are referring is used to normalize the queries points, so they match the scale of `normal_eps`. I hope this helps.
