### ISSUE TITLE
Can I reduce Polygon count?

### ISSUE THREAD

**Issue by MicKkmack** [NVlabs/neuralangelo#181]
Hi , 

I've managed to get some good results , but I'm struggling to load them due to the amount of polygons. 

I'm getting around 15,000,000 polygons, whereas Nerf Studio gives me around 50,000 , does anyone know if there is a parameter to lower this or what causes that many polygons?

Thanks! :)

**Comment by Bombaninha** [comment]
Lower **RESOLUTION** to reduce the mesh size during the isosurface extraction stage:

```bash
CHECKPOINT=logs/${GROUP}/${NAME}/xxx.pt
OUTPUT_MESH=xxx.ply
CONFIG=logs/${GROUP}/${NAME}/config.yaml
RESOLUTION=2048
BLOCK_RES=128
GPUS=1  # use >1 for multi-GPU mesh extraction
torchrun --nproc_per_node=${GPUS} projects/neuralangelo/scripts/extract_mesh.py \
    --config=${CONFIG} \
    --checkpoint=${CHECKPOINT} \
    --output_file=${OUTPUT_MESH} \
    --resolution=${RESOLUTION} \
    --block_res=${BLOCK_RES}
```

**Comment by MicKkmack** [comment]
> Lower **RESOLUTION** to reduce the mesh size during the isosurface extraction stage:
> 
> ```shell
> CHECKPOINT=logs/${GROUP}/${NAME}/xxx.pt
> OUTPUT_MESH=xxx.ply
> CONFIG=logs/${GROUP}/${NAME}/config.yaml
> RESOLUTION=2048
> BLOCK_RES=128
> GPUS=1  # use >1 for multi-GPU mesh extraction
> torchrun --nproc_per_node=${GPUS} projects/neuralangelo/scripts/extract_mesh.py \
>     --config=${CONFIG} \
>     --checkpoint=${CHECKPOINT} \
>     --output_file=${OUTPUT_MESH} \
>     --resolution=${RESOLUTION} \
>     --block_res=${BLOCK_RES}
> ```

Thanks a lot, that worked :)

**Comment by camolina2** [comment]
Hi,

I was wondering if there is a way to extract the mesh in parts. I am running out of GPU memory for the extraction, and I would like to achieve a better resolution.

Thank you!
