### ISSUE TITLE
PLY TO OBJ Files

### ISSUE THREAD

**Issue by MicKkmack** [NVlabs/neuralangelo#185]
Hi , 

Does anyone know if Neuralangelo can be adjusted to create OBJ files rather than the PLY files it creates?

Thanks :)

**Comment by MachtaYassine** [comment]
It uses Trimesh, So i think naming your output mesh 'mesh.obj' should work. Did you try that ?

**Comment by MicKkmack** [comment]
I just did , it worked thank you! I should of thought of that...
