### ISSUE TITLE
MacBook Pro M1 compatibility

### ISSUE THREAD

**Issue by thomas5674** [NVlabs/neuralangelo#188]
Hi,

Thank you for your nice work!
I'm working with a MacBook Pro (Apple M1 Pro, 2021) and tried to install the necessary packages to run your code.
However, the cudatoolkit is not compatible with my laptop. Are there any workarounds to run your code on a Macbook?

Thank you in advance!

Kind regards,
Thomas

**Comment by mli0603** [comment]
Hi @thomas5674 

We currently only support CUDA compatible graphics cards.
