### ISSUE TITLE
What is the difference between numerical taps 4 and 6？

### ISSUE THREAD

**Issue by mowangmodi** [NVlabs/neuralangelo#190]
I see that the default value for the tag is 4, so can I ask what is the difference between the numeric tags 4 and 6?

**Comment by mli0603** [comment]
Hi @mowangmodi 

Thank you for your interest in our work. Using 4 taps is a faster approximation of the analytical gradient where only 4 points are queried to compute the finite differences, but less accurate compared to 6 taps. Using 4 taps would speed up the convergence with a little sacrifice of the quality. 

I hope this helps!
