### ISSUE TITLE
CondaEnvException: Pip failed------failed to build tinycudann 

### ISSUE THREAD

**Issue by zhanglingyun** [NVlabs/neuralangelo#194]
run `conda env create --file neuralangelo.yaml`
and get this
![2024-03-28_17152023](https://github.com/NVlabs/neuralangelo/assets/10289571/5e9d89a9-136e-4cb2-89fb-f503e1f6aed4)
How can I solve it

**Comment by NickWilde** [comment]
I met silimar error yesterday, to me it seems a general error, so you could try doing the following and see if it works:
1. Build Pytorch with cuda before executing conda install.
2. edit neuralangelo.yaml and remove the part with pip.
3. in your .bashrc file export PATH to cuda and LD_LIBRARY_PATH to cuda/lib64
4. After conda finish creating the environment, first activate the environment by `conda activate neuralangelo`, then run `pip install -r ./requirements.txt` to continue the installation.

even though it says "your cuda is 11.7 which mismatch the version used to compile Pytorch, it should not be a problem". I still suggest you install a new cuda and use it to compile Pytorch.

Hope this will help

**Comment by zhanglingyun** [comment]
> I met silimar error yesterday, to me it seems a general error, so you could try doing the following and see if it works:
> 
> 1. Build Pytorch with cuda before executing conda install.
> 2. edit neuralangelo.yaml and remove the part with pip.
> 3. in your .bashrc file export PATH to cuda and LD_LIBRARY_PATH to cuda/lib64
> 4. After conda finish creating the environment, first activate the environment by `conda activate neuralangelo`, then run `pip install -r ./requirements.txt` to continue the installation.
> 
> even though it says "your cuda is 11.7 which mismatch the version used to compile Pytorch, it should not be a problem". I still suggest you install a new cuda and use it to compile Pytorch.
> 
> Hope this will help

Thanks.I give up to use docker then. I 'm not sure whether .bashrc file could set multiple cuda values but I may run many software.Emm,I think docker may be suitable.But thank you again then.
