### ISSUE TITLE
where is the neuralangelo.datasets.json_data

### ISSUE THREAD

**Issue by jianglh-WHU** [NVlabs/neuralangelo#2]
hi~thanks for your excellent work!

When I tried to run the Neuralangelo code using the instant-ngp fox dataset with the default template config, I encountered an error stating `No module named 'projects.neuralangelo.datasets'`

 I would appreciate it if you could do me a favor!

**Comment by chenhsuanlin** [comment]
I have pushed a fix to correct the path in the template config `custom/template.yaml`. However, please note that this config is not meant to work out of the box, but rather just an example of what you could customize. If you want to work with your custom data, please follow the [data preparation](https://github.com/NVlabs/neuralangelo/blob/main/DATA_PROCESSING.md) instructions to auto-generate the config file.
