### ISSUE TITLE
Google Colab please

### ISSUE THREAD

**Issue by ozhenn** [NVlabs/neuralangelo#26]
Please publish the Google Colab notebook for testing opportunities.

**Comment by chenhsuanlin** [comment]
Thanks @ozhenn for the suggestion -- this is on our todo list, and we are evaluating ways to make this available. In the meantime, PRs are always welcome. 😄

**Comment by chenhsuanlin** [comment]
The colab notebook has been added! https://colab.research.google.com/drive/13u8DX9BNzQwiyPPCB7_4DbSxiQ5-_nGF. Closing as task is complete.
