### ISSUE TITLE
Inference time on test set

### ISSUE THREAD

**Issue by smandava98** [NVlabs/neuralangelo#32]
Hi. Is there info on how long it took to run Neuralangelo on videos from your test set or other in the wild videos?
I see the inference speed in seconds 
<img width="623" alt="Screen Shot 2023-08-17 at 9 28 50 AM" src="https://github.com/NVlabs/neuralangelo/assets/22734015/7dd0af86-16f4-4dcb-be49-8e6bc5fbf2f4">

I read through your paper and am still trying to understand certain components so I am not sure if this table is regarding a particular step in Neuralangelo or the entire pipeline as a whole?

**Comment by mli0603** [comment]
Inference time is for mesh extracting mesh of 128^3 resolution. Details can be found in Appendix E Computation Time.
