### ISSUE TITLE
automatically save last epoch

### ISSUE THREAD

**Issue by chris-aeviator** [NVlabs/neuralangelo#33]
currently checkpoints will only be saved at the configured checkpoint interval.

When running for 50000 iterations, with checkpoints set to save every 20000 iterations, I will get a final checkpoint of iteration 40000 even though my training ran to 50000.

When checkpoint_interval < total_checkpoints, the training runs but doesnt save any checkpoints due to the same reason.

**Comment by mli0603** [comment]
Hi @chris-aeviator 

Confirmed. Working on a fix.

**Comment by mli0603** [comment]
Fixed in PR https://github.com/NVlabs/neuralangelo/pull/34
