### ISSUE TITLE
![微信图片_20230818110742](https://github.com/NVlabs/neuralangelo/assets/88806366/04341bf0-291f-4344-8ee1-fdf19ade1795)

### ISSUE THREAD

**Issue by WM362426** [NVlabs/neuralangelo#36]
![微信图片_20230818110742](https://github.com/NVlabs/neuralangelo/assets/88806366/04341bf0-291f-4344-8ee1-fdf19ade1795)

_Originally posted by @WM362426 in https://github.com/NVlabs/neuralangelo/issues/35#issuecomment-1683271917_

**Comment by chenhsuanlin** [comment]
Closing (insufficient content).
