### ISSUE TITLE
Removing redundant part

### ISSUE THREAD

**Issue by fzy139** [NVlabs/neuralangelo#37]
Hi,

Thanks for your excellent work. I am trying to test on nerf_synthetic dataset,  following the data preparation to convert the format and using the base.yaml config. I find the quality is perfect except the geometry. 

There is some redundant part on the bottom of the model. Is that reasonable with some post-processing, or there is something I missed?

Thanks

![image](https://github.com/NVlabs/neuralangelo/assets/34181155/2c7bdbea-cce4-41eb-adbd-0a6ba829a36b)
![image](https://github.com/NVlabs/neuralangelo/assets/34181155/d9464121-0842-4c9b-888a-61869c1ce65d)

**Comment by mli0603** [comment]
Hi @fzy139 

Thank you for your interest in the project!

This is a good question. The bottom of the Lego is never observed directly by any image. What's worse, it is entirely white and there are many ways to explain away the RGB observation. The current reconstruction is simply one of the millions of plausible ways for the white color. In summary, this is a very ill-posed problem unless there is additional information (such as the prior knowledge of white color == empty space).

I hope this helps.

**Comment by fzy139** [comment]
Thanks for your fast reply!

I see. The texture-less region is very hard to reconstruct. I will try some tricks to fix it.
