### ISSUE TITLE
How to use checkpoint correctly

### ISSUE THREAD

**Issue by shewangmu** [NVlabs/neuralangelo#40]
After training, I got the xxx.pt with 160000 iterations. When I use the script to extract mesh, the mesh was extracted correctly.
But when I use
"torchrun --nproc_per_node=4 train.py --logdir=logs/object_new --config configs/object.yaml --show_pbar --wandb --checkpoint xxx.pt"
to continue training, the vis result before the first epoch was totally different than the previous training in 1600000 iterations (much worse than the previous one). What should I do

**Comment by shewangmu** [comment]
Besides, there is a tiny bug in line 38 of method extract_mesh() in project/neuralangelo/utils/mesh.py when --single_gpu is used. Distribution initialization should be checked.

**Comment by shewangmu** [comment]
> After training, I got the xxx.pt with 160000 iterations. When I use the script to extract mesh, the mesh was extracted correctly. But when I use "torchrun --nproc_per_node=4 train.py --logdir=logs/object_new --config configs/object.yaml --show_pbar --wandb --checkpoint xxx.pt" to continue training, the vis result before the first epoch was totally different than the previous training in 1600000 iterations (much worse than the previous one). What should I do

solved! I should use --resume to load iteration as well since coarse2fine strategy was used.

**Comment by shewangmu** [comment]
Salute! Li, Zhaoshuo and M\"uller, Thomas and Evans, Alex and Taylor, Russell H and Unberath, Mathias and Liu, Ming-Yu and Lin, Chen-Hsuan! Thank you for your amazing work and sharing!

**Comment by chenhsuanlin** [comment]
> Besides, there is a tiny bug in line 38 of method extract_mesh() in project/neuralangelo/utils/mesh.py when --single_gpu is used. Distribution initialization should be checked.

@shewangmu It would be great if you could also help submit a PR if you've identified a bug here. Thanks!

**Comment by chenhsuanlin** [comment]
Quickly fixed this in a27dded, closing again!
