### ISSUE TITLE
maybe incorrect bounding box in convert_tnt_to_json.py

### ISSUE THREAD

**Issue by Willyzw** [NVlabs/neuralangelo#43]
https://github.com/NVlabs/neuralangelo/blob/2213bb3733267c021f8cbf7651bcb39b4804d4d9/projects/neuralangelo/scripts/convert_tnt_to_json.py#L167

thanks for sharing the awesome code. I notice a potential bug at the aforementioned line. Should it be firstly min and then max?

**Comment by mli0603** [comment]
Nice catch! Fixed in commit https://github.com/NVlabs/neuralangelo/commit/62483febb00c9ad4b8a17884abf9191acc6cafa9
