### ISSUE TITLE
Remove 'logdir' from mesh extraction command 

### ISSUE THREAD

**Issue by chris-aeviator** [NVlabs/neuralangelo#46]
due to logdir arg have been removed in https://github.com/NVlabs/neuralangelo/commit/ac0c5c5ea0e24e94b311aafabe9b84614d92fb30#diff-44a547ebc95ebb91f20357daee9cf470d336a221dfed1faf16d61957fb3f8ad4L31 , the mesh extraction script will error with 

KeyError: "The input key 'logdir; does not exist in the config files." when used as in the readme.

The logdir arg should be stripped from the readme.

**Comment by chenhsuanlin** [comment]
Thanks @chris-aeviator, `--logdir` should already have been stripped out from the README as of deb9b4562.
