### ISSUE TITLE
Error 403 (Forbidden) when accessing data_DTU.zip

### ISSUE THREAD

**Issue by db-ol** [NVlabs/neuralangelo#5]
The `preprocess_dtu.sh` seems to be encountering an issue, as there is an "access denied" error while attempting to access the `data_DTU.zip` through the provided Google Drive link `1zgD-uTLjO8hXcjLqelU444rwS9s9-Syg`. Would it be possible to consider adjusting the permission to "Anyone with the link", assuming that the intention is to make it accessible to the public? Thank you, @chenhsuanlin .

```shell
$ bash projects/neuralangelo/scripts/preprocess_dtu.sh ${PATH_TO_DTU}
Download DTU data
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1zgD-uTLjO8hXcjLqelU444rwS9s9-Syg 

unzip:  cannot find or open data_DTU.zip, data_DTU.zip.zip or data_DTU.zip.ZIP.
rm: cannot remove 'data_DTU.zip': No such file or directory
Generate json files

```

**Comment by Nacriema** [comment]
Hi, you can download available DTU dataset from the original page here: http://roboimagedata.compute.dtu.dk/?page_id=36

**Comment by mli0603** [comment]
Hi @db-ol 

Thank you for your interest in the project.

Let me push a update to fix this issue.

**Comment by mli0603** [comment]
Hi @db-ol 

Can you see if the commit (https://github.com/NVlabs/neuralangelo/commit/3ef201b4ee0853bc77febf6921b422c35dbdabfa) fixes your issue?

**Comment by db-ol** [comment]
Thanks @Nacriema for your information. Yes, just some renaming and file structure reorganizing are required if we directly got from the original page.

Thanks @mli0603 for fixing it!
