### ISSUE TITLE
Number of epochs

### ISSUE THREAD

**Issue by smtabatabaie** [NVlabs/neuralangelo#6]
Hi everyone, I'm training with the following command from readme file:
```
EXPERIMENT=toy_example
GROUP=example_group
NAME=example_name
CONFIG=projects/neuralangelo/configs/custom/${EXPERIMENT}.yaml
GPUS=1  # use >1 for multi-GPU training!
torchrun --nproc_per_node=${GPUS} train.py \
    --logdir=logs/${GROUP}/${NAME} \
    --config=${CONFIG} \
    --show_pbar
```
It's currently running and is in Epoch number 1200. I read the files and there's a max_epoch parameter, which is set to 9999999999. I wanted to ask what is the normal and optimal epoch number, and should I change anything in the code before running the command?
Thanks

**Comment by chenhsuanlin** [comment]
Epochs don't mean much in this context so please feel free to ignore the displayed epoch number, and `max_epoch` is not used here so it's simply set to a very large number. We measure by iterations here, and `max_iter` is what matters.
