### ISSUE TITLE
Suggested way to view .ply and easily fly around that is not Blender?

### ISSUE THREAD

**Issue by smandava98** [NVlabs/neuralangelo#61]
Hi. Thanks for the consistent support to all the developers on here. It is much appreciated :)

I have one question regarding viewing the .ply files:
Is there a faster, more user friendly alternative to Blender? I tried viewing some .ply files for the Tanks and Temples dataset and even that has a lot of missing points so the object is not shown clearly (and is missing texture and various colors). I viewed a sample run on my own video and it took looks unclear.

I am wondering how you guys made those video of you flying around the neural reconstructions? I am looking for a better way to visualize full scenes

**Comment by chenhsuanlin** [comment]
The fly-throughs camera trajectories and visualizations were rendered with Blender -- it requires some manual effort to create the effects. We also have a notebook for interactively visualizing the meshes, which I can push later.

**Comment by smandava98** [comment]
Thanks. Looking forwards to using the notebook then
