### ISSUE TITLE
Still no texture after add the --textured

### ISSUE THREAD

**Issue by dolcelee** [NVlabs/neuralangelo#62]
First of all, amazing work! 
I tried a portrait dataset, the mesh looks good. However, it still shows no texture after I added "--textured". I use Meshlab and Blender to view ply files. Did I miss anything?
![微信截图_20230823102757](https://github.com/NVlabs/neuralangelo/assets/1515676/da14cad2-a24b-4dd7-950b-11f698ff1592)
CHECKPOINT=logs/example_group/example_name/xxx.pt
OUTPUT_MESH=xxx.ply
CONFIG=projects/neuralangelo/configs/custom/${EXPERIMENT}.yaml
RESOLUTION=2048
BLOCK_RES=128
GPUS=1  # use >1 for multi-GPU mesh extraction
torchrun --nproc_per_node=${GPUS} projects/neuralangelo/scripts/extract_mesh.py \
    --config=${CONFIG} \
    --checkpoint=${CHECKPOINT} \
    --output_file=${OUTPUT_MESH} \
    --resolution=${RESOLUTION} \
    --block_res=${BLOCK_RES} \
    --textured

**Comment by chenhsuanlin** [comment]
Thanks for reporting. This is a known bug, will fix it in the coming days.

**Comment by ftn-gautam** [comment]
I see the same issue but for me, it shows texture if I use the first checkpoint but no texture for checkpoints after the first one.

**Comment by Bai426** [comment]
I have the same issue.

**Comment by dolcelee** [comment]
> @chenhsuanlin Is it really a bug? It didn't work for me when I wrote it the way the author of the issue did, but when I wrote it the different way everything worked. Just placed the command in the beginning and added backlash after it.
> 
> --textured --config=${CONFIG} --checkpoint=${CHECKPOINT} --output_file=${OUTPUT_MESH} --resolution=${RESOLUTION} --block_res=${BLOCK_RES}

Thanks for the data point, I tried this way but still didn't work. However, when I changed to the first checkpoint instead of others, the texture shows.

**Comment by dolcelee** [comment]
> I see the same issue but for me, it shows texture if I use the first checkpoint but no texture for checkpoints after the first one.
![微信图片_20230824102043](https://github.com/NVlabs/neuralangelo/assets/1515676/5293c944-2604-4b14-a48f-5197803e4988)

Thanks for the data point, I tried the first checkpoint, the texture shows as you said! The performance is not good unfortunately

**Comment by Bai426** [comment]
@dolcelee Sorry, I didn't see the texture yet with the first checkpoint and the above scripts, not mentioned using other checkpoints. I also noticed that the 3d model is very rough in the first checkpoint.

**Comment by mli0603** [comment]
Hi all, 

Sorry for the late reply.

Can anyone confirm if they see an output of "Failed to convert color" in the terminal when there is no color?

**Comment by dolcelee** [comment]
@mli0603 

- I didn't see any error message in the terminal when there is no color. It shows color[127,127,127,255] something...
- https://drive.google.com/drive/folders/1hXICgwaB3ak8mk6KGvy4EksRz87CN3m4?usp=sharing
- I uploaded my dataset, contact me if you need anything else

**Comment by mli0603** [comment]
Thank you @dolcelee 

This is likely a bug related to #75 where the loaded checkpoints fail to predict any colors. We are looking into this now and will circle back.

**Comment by Bai426** [comment]
Thank you very much, I will let you know my test.

Best,
Mike

**Comment by dolcelee** [comment]
@mli0603 
I retrained the same dataset and regenerated the mesh. It shows the texture but looks weird. I think this problem is related to the bounding sphere. Could you please tell me how to set the value of the sphere?
![_tmp_dingtalkgov_qt_pic_1693444522195](https://github.com/NVlabs/neuralangelo/assets/1515676/d874214b-9831-47ef-97aa-3db8d1f64e98)

**Comment by mli0603** [comment]
Hi @dolcelee 

Good to know that textured mesh can be extracted. For sphere adjustment, please see [DATA PREPROCESSING](https://github.com/NVlabs/neuralangelo/blob/main/DATA_PROCESSING.md).

**Comment by mli0603** [comment]
Closing this issue as it is resolved. For other issues, feel free to report in a separate thread.

**Comment by lie12huo** [comment]
@mli0603 
I used the latest version of the code, but the exported mesh still has no texture. Is there anything else I need to pay attention to?My export script is as follows：

_GROUP=fc_example
NAME=fc_example_0831
CHECKPOINT=logs/${GROUP}/${NAME}/epoch_00053_iteration_000020000_checkpoint.pt
OUTPUT_MESH=yzfc_53.ply
CONFIG=logs/${GROUP}/${NAME}/config.yaml
RESOLUTION=2048
BLOCK_RES=128
GPUS=1  # use >1 for multi-GPU mesh extraction
torchrun --nproc_per_node=${GPUS} projects/neuralangelo/scripts/extract_mesh.py \
    --textured \
    --config=${CONFIG} \
    --checkpoint=${CHECKPOINT} \
    --output_file=${OUTPUT_MESH} \
    --resolution=${RESOLUTION} \
    --block_res=${BLOCK_RES}_
![ad060d8b14109908a918917cdec8aea](https://github.com/NVlabs/neuralangelo/assets/52315796/93dcf9d0-ee4f-4aaa-a61b-c5162922397a)

**Comment by chenhsuanlin** [comment]
@lie12huo the checkpoint is likely corrupted from the previous (buggy) code. You would need to retrain the model for this case, not just re-extract the mesh.

**Comment by lie12huo** [comment]
@chenhsuanlin 
I used the latest code to preprocess and train checkpoints today, but the exported model still has no texture.
![image](https://github.com/NVlabs/neuralangelo/assets/52315796/40ec907b-c8f4-459d-9865-caf246f2b77f)
