### ISSUE TITLE
I run neuralangelo on pure Ubuntu 22.04 LTS. This is normal ?

### ISSUE THREAD

**Issue by altava-sgp** [NVlabs/neuralangelo#73]
![image](https://github.com/NVlabs/neuralangelo/assets/133635323/21a63789-fc21-4cd9-8aec-54c554c429ba)

It shows only "0%" now.
What can I do now ?
There is no GUI like instant-ngp ?

**Comment by chenhsuanlin** [comment]
It's training now, so congratulations! There's no GUI for Neuralangelo. The progress bar should be updating, but with your setup it's 1 iteration per epoch so it would look like it's always at the start of the epoch (0%).

**Comment by altava-sgp** [comment]
@chenhsuanlin 
Ok. Good. How much time will it take ? :thinking:

**Comment by chenhsuanlin** [comment]
Please see #4
