### ISSUE TITLE
Poor performance on DTU dataset

### ISSUE THREAD

**Issue by Runsong123** [NVlabs/neuralangelo#74]
Dear author, 

Thanks for your great work and detailed guidance.
Here is my results on DTU and there is notable variations with the reported number in paper. Is it the expected variance? BTW, the similar phenomenon was also observed by #65.  Looking forward to your reply.

**Implementation details:**
1. linux machine with a 3090 GPU; Cuda:11.8; Pytorch:2.00
2. The evaluation code was borrowed from NeuralUDF. Also, the performance on 106 shape was almost aligned with the paper.

**The metric results:**
![image](https://github.com/NVlabs/neuralangelo/assets/39645074/47593c8c-eb36-461b-a51a-6e7677fa8b7f)

**Some visual results:**
a). recovering the details for shape 24:
![image](https://github.com/NVlabs/neuralangelo/assets/39645074/d5e7d6c5-672c-45fb-9cc9-3b62e481fdab)

b). Introducing the undesired artifacts on shape 69:
![image](https://github.com/NVlabs/neuralangelo/assets/39645074/184c05dd-314a-4564-a2bb-ef2db564c2da)

Bests,
Runsong

**Comment by FangjinhuaWang** [comment]
Hi, I am also curious about this. Did you try cleaning the mesh with masks before evaluation? Mesh cleaning can increase the accuracy, but the completeness may drop a bit. If you did not clean the mesh, you may try this [script](https://github.com/xxlong0/SparseNeuS/blob/main/evaluation/clean_mesh.py) from SparseNeuS.
![image](https://github.com/NVlabs/neuralangelo/assets/45430667/aa7802ce-5441-4f7a-a5db-4a4ba55a564c)

**Comment by Runsong123** [comment]
> Hi, I am also curious about this. Did you try cleaning the mesh with masks before evaluation? Mesh cleaning can increase the accuracy, but the completeness may drop a bit. If you did not clean the mesh, you may try this [script](https://github.com/xxlong0/SparseNeuS/blob/main/evaluation/clean_mesh.py) from SparseNeuS. ![image](https://user-images.githubusercontent.com/45430667/263193329-aa7802ce-5441-4f7a-a5db-4a4ba55a564c.png)

Hi, I use the mesh after cleaning to calculate the metric. For mesh clean, I use the script in [NeuralUDF](https://github.com/xxlong0/NeuralUDF/blob/main/evaluation/clean_dtu_mesh.py). I think the clean code is the same in SparseNeus. Here are the mesh before cleaning and after cleaning. 


![image](https://github.com/NVlabs/neuralangelo/assets/39645074/8683b3ce-799a-4e4b-b3b4-b42e5d8ab4ec)

![image](https://github.com/NVlabs/neuralangelo/assets/39645074/125b31c1-c4db-482a-99bb-1082c2edbbee)


Bests,
Runsong

**Comment by Runsong123** [comment]
> Dear author,
> 
> Thanks for your great work and detailed guidance. Here is my results on DTU and there is notable variations with the reported number in paper. Is it the expected variance? BTW, the similar phenomenon was also observed by #65. Looking forward to your reply.
> 
> **Implementation details:**
> 
> 1. linux machine with a 3090 GPU; Cuda:11.8; Pytorch:2.00
> 2. The evaluation code was borrowed from NeuralUDF. Also, the performance on 106 shape was almost aligned with the paper.
> 
> **The metric results:** ![image](https://user-images.githubusercontent.com/39645074/263036267-47593c8c-eb36-461b-a51a-6e7677fa8b7f.png)
> 
> **Some visual results:** a). recovering the details for shape 24: ![image](https://user-images.githubusercontent.com/39645074/263039456-d5e7d6c5-672c-45fb-9cc9-3b62e481fdab.png)
> 
> b). Introducing the undesired artifacts on shape 69: ![image](https://user-images.githubusercontent.com/39645074/263040282-184c05dd-314a-4564-a2bb-ef2db564c2da.png)
> 
> Bests, Runsong

Sorry, I realized the uploaded images were not the final results after cleaning. Here are the visualizations of meshes for the final evaluation. 
**Nonetheless**, I can still see the reconstructed mesh was not accurate (e.g., the wrong topology). For comparison, I  add the neus's result after cleaning.

![image](https://github.com/NVlabs/neuralangelo/assets/39645074/3732ea13-8ba6-4ddb-945f-02e11a5a1f35)

![image](https://github.com/NVlabs/neuralangelo/assets/39645074/6a796216-205a-492b-a054-8ec2f8f3ffa5)

![image](https://github.com/NVlabs/neuralangelo/assets/39645074/3f5e71e1-0e02-4344-8328-3f1e3fd0831d)

**Comment by FangjinhuaWang** [comment]
I see. Then the problem should not be mesh cleaning.

**Comment by mli0603** [comment]
Hi @Runsong123 

Thank you for reporting. We will look into this. I will close this and move all related discussions to #65. Feel free to follow up there.
