### ISSUE TITLE
I could run the custom training and Generate FILES，How do I see the resulting model Or how do I use this training result to convert a 2d video to 3d

### ISSUE THREAD

**Issue by yuxuJava789** [NVlabs/neuralangelo#76]
Hi, I could run the custom training and Generate the following files. But I'm not sure if this is the correct result

![image](https://github.com/NVlabs/neuralangelo/assets/36221896/4215ad58-62e3-4e94-a10d-3d77312be7bc)

QUESTION：
              if successful，How do I see the resulting model Or how do I use this training result to convert a 2d video to 3d

**Comment by chenhsuanlin** [comment]
Hi @yuxuJava789, this looks like it's training well. Please see [this section](https://github.com/NVlabs/neuralangelo#isosurface-extraction) on instructions for mesh extraction.

**Comment by yuxuJava789** [comment]
@chenhsuanlin  Thanks for your answer, I now have the .ply file, but I have one more question.
I use a car video to get a .ply file through training. If I now have a new car video, do I have to go through the following steps to get the .ply file:
First: DATA_PROCESSING:
                 1. Preprocessing the data and running COLMAP,
                 2. inspecting and refining the bounding sphere of interest for running Neuralangelo.

Second: Run Neuralangelo!

Third: Isosurface extraction

Is it difficult to get the .ply file every time there is a new video?

**Comment by yuxuJava789** [comment]
Hi @chenhsuanlin Thanks for your answer, I now have the .ply file, but I have one more question.
I use a car video to get a .ply file through training. If I now have a new car video, do I have to go through the following steps to get the .ply file:
First: DATA_PROCESSING:
                 1. Preprocessing the data and running COLMAP,
                 2. inspecting and refining the bounding sphere of interest for running Neuralangelo.

Second: Run Neuralangelo!

Third: Isosurface extraction

Is it necessary to perform the above three steps to get the .ply file every time there is a new video?
