### ISSUE TITLE
train.py FAILED

### ISSUE THREAD

**Issue by Islaster** [NVlabs/neuralangelo#77]
I've downloaded the AI and now I'm trying to run it with the example given in the readME and I get this error "train.py FAILED"

SOFTWARE:
- Windows 10
- ubuntu-wsl 
- Python Anaconda

HARDWARE:
- GeForce 4070 ti
- 208 ram
- SUPERMICRO MOTHERBOARD

**Comment by Islaster** [comment]
![image](https://github.com/NVlabs/neuralangelo/assets/52678788/f9d3e4e4-0e50-4da1-ad5d-c44450cb7588)

**Comment by chenhsuanlin** [comment]
Hi @Islaster, I just pushed a fix (fe82909) to `main`, could you pull and try again?

**Comment by Islaster** [comment]
I changed EXPERIMENT to template and it got me this new error
![image](https://github.com/NVlabs/neuralangelo/assets/52678788/6574b926-ac70-4cbf-b921-8ab3cf6e4c9e)

**Comment by Islaster** [comment]
FYI i did the pull prior to new error

**Comment by Islaster** [comment]
I forgot to do data preparation lol i think I've figured it out
