### ISSUE TITLE
Result mesh is very poor for indoor scenes

### ISSUE THREAD

**Issue by smandava98** [NVlabs/neuralangelo#78]
Hello, I took a video of an indoor scene but only from a frontal view (so I did not have the camera move around the whole room but just a part of it) and I initially expected myself to get color results of that portion where I can move in and out to view objects but the resulting mesh is this colorless blob looking object. I ran the full training loop (500k iterations with no changes in hyperparameters). How were you able to get such good looking meshes from your dataset? Does the data need additional requirements?

When I look at the wandb validation images they look great. It seems to be capturing all details well. Its just the mesh part that looks very off..I just want to somehow get a 3D scene of those wandb images.

Followup: Also why doesn't the mesh come with colors?

<img width="847" alt="Screen Shot 2023-08-25 at 6 53 20 PM" src="https://github.com/NVlabs/neuralangelo/assets/22734015/9927fd8e-40f6-4e80-bd0d-775a0c1fe300">

**Comment by smandava98** [comment]
Also why doesn't it display color?

**Comment by chenhsuanlin** [comment]
Hi @smandava98, regarding your questions:
- Have you set the `scene_type` to be `indoor` in the data processing step?
- Have you tried looking inside the blob?
- Please see #62 for issues on textured mesh extraction

**Comment by mli0603** [comment]
Hi @smandava98 

Sorry for the late reply. 

- Have you looked at the normal maps? Do they look reasonable?
- If normal maps look great, my best guess is that your reconstruction result is **inside** the blob that you are looking at. You can zoom into the blob to look around. Another trick is to visualize the camera poses and mesh together to locate the reconstruction.

I hope these help!

**Comment by mli0603** [comment]
We have pushed a commit that potentially fixes the issue of mesh extraction (https://github.com/NVlabs/neuralangelo/commit/c91af8d5098c858df8e8dfa35fba8666d314782b). Please let us know if you still run into the same problem.

**Comment by smandava98** [comment]
Thanks both! I will try it out with that and experiment further with better ways to visualize it. Feel free to close the issue and I can re-open it if further need is there. Thanks again for the help.
