### ISSUE TITLE
Guide or Tutorial?

### ISSUE THREAD

**Issue by Islaster** [NVlabs/neuralangelo#79]
is there a guide out to explain each step? I'm right now epoch training and wondering how many epochs get trained is it a set amount or is it dynamic depending on some other variable. How do I get the end product?

**Comment by chenhsuanlin** [comment]
Hi @Islaster, the training length is determined by `max_iter`. Please see [this section](https://github.com/NVlabs/neuralangelo#isosurface-extraction) on extracting the mesh. The README is the guide -- if there is any part that is unclear, please let us know.

**Comment by Islaster** [comment]
how do i change max iter
