### ISSUE TITLE
Do I need to perform the above three steps to get the .ply file every time there is a new video?

### ISSUE THREAD

**Issue by yuxuJava789** [NVlabs/neuralangelo#81]
Hi @chenhsuanlin Thanks for your answer, I now have the .ply file, but I have one more question.
I use a car video to get a .ply file through training. If I now have a new car video, do I have to go through the following steps to get the .ply file:
First: DATA_PROCESSING:
1. Preprocessing the data and running COLMAP,
2. inspecting and refining the bounding sphere of interest for running Neuralangelo.

Second: Run Neuralangelo!

Third: Isosurface extraction

Is it necessary to perform the above three steps to get the .ply file every time there is a new video?

**Comment by chenhsuanlin** [comment]
Hi @yuxuJava789, different videos are treated as different datasets, so yes you would need to rerun the entire pipeline for each vidoe.
