### ISSUE TITLE
TIPS & SETTINGS

### ISSUE THREAD

**Issue by Islaster** [NVlabs/neuralangelo#82]
How do I change setting such as max-iter and epoch. It would be good to put prerequisites installations and bare minimum requirements for software and hardware(i.e. everything you need to successfully download it via conda or the setup the docker needs in order to run). Thanks for sharing this amazing piece of software.

**Comment by mli0603** [comment]
Hi @Islaster 

The `max-iter` is defined [here](https://github.com/NVlabs/neuralangelo/blob/main/projects/neuralangelo/configs/base.yaml#L13). You can add this line to your own config with updated values. This will overwrite the default value.

**Comment by chenhsuanlin** [comment]
We should already have all the instructions and minimal requirements in the README. Please let us know if there is any part that is unclear.
