### ISSUE TITLE
Normal map error

### ISSUE THREAD

**Issue by ZPzhu** [NVlabs/neuralangelo#91]
Great work! One problem in Normal map. Could anyone give me some advices?
  
![error](https://github.com/NVlabs/neuralangelo/assets/51941034/0b171490-903e-4693-bca9-a23aacacd431)

**Comment by mli0603** [comment]
Hi @ZPzhu 

Based on the normal and opacity map, the bounding regions are likely wrong.

- We have updated the pre-processing scripts, especially the bounding region estimation. Can you try the latest code on the main branch?
- You can also inspect and modify the bounding regions following the instructions [here](https://github.com/NVlabs/neuralangelo/blob/main/DATA_PROCESSING.md#inspect-and-adjust-colmap-results)

**Comment by ZPzhu** [comment]
> Hi @ZPzhu
> 
> Based on the normal and opacity map, the bounding regions are likely wrong.
> 
> * We have updated the pre-processing scripts, especially the bounding region estimation. Can you try the latest code on the main branch?
> * You can also inspect and modify the bounding regions following the instructions [here](https://github.com/NVlabs/neuralangelo/blob/main/DATA_PROCESSING.md#inspect-and-adjust-colmap-results)

The problem has been solved.Thanks!!!
