### ISSUE TITLE
Mesh bad even though training shows good results

### ISSUE THREAD

**Issue by deeepwin** [NVlabs/neuralangelo#95]
I have trained on DTU65 with good results. I am now training on custom data - a scan of a Logitech mouse - with latest commit. The training looks gut after 500k steps, with nice normals and rendering:

![image](https://github.com/NVlabs/neuralangelo/assets/65670300/73788339-a474-437f-84a7-550e940adf58)

Nevertheless, when I mesh it according to instructions, the output is completely wrong, as you can see here:

<img width="734" alt="mesh" src="https://github.com/NVlabs/neuralangelo/assets/65670300/39ccfab2-ec6f-4a7d-9bf4-6351e226178f">

The bounding sphere could be optimized, but as training appears successful, there seems to be something wrong with the meshing.

<img width="431" alt="preprocessing" src="https://github.com/NVlabs/neuralangelo/assets/65670300/225a6b23-773b-4915-b0cd-59d2965e3716">

What could be the problem here? Is there a setting in mesh generation that need to be adjusted? I have seen that others had issue with meshing from particular checkpoint. Here my code:

```
# mouse-2
EXPERIMENT=custom/mouse-2
CHECKPOINT=logs/neuralangelo/mouse-2/epoch_01683_iteration_000500000_checkpoint.pt
OUTPUT_MESH=mouse-2_mesh.ply
RESOLUTION=2048
BLOCK_RES=128

# generate mesh
torchrun projects/neuralangelo/scripts/extract_mesh.py \
    --config=${CONFIG} \
    --checkpoint=${CHECKPOINT} \
    --output_file=${OUTPUT_MESH} \
    --resolution=${RESOLUTION} \
    --block_res=${BLOCK_RES} \
    --textured
``` 

Any help would be appreciated.

**Comment by Dragonkingpan** [comment]
The estimated camera pose during the colmap stage for things with no surface features is inaccurate, so the generated image is very poor

**Comment by deeepwin** [comment]
> The estimated camera pose during the colmap stage for things with no surface features is inaccurate, so the generated image is very poor

But the poses look actually quite accurate as they move very consistently. Also the rendered image for evaluation looks very close to the target. Or, which generated image do you mean is very poor?

**Comment by dolcelee** [comment]
I met the same problem. I imported my colmap data into the blender and the bounding sphere looks tight, but the generated mesh is not even close to my data. The mesh was much better before they update the texture fix commit.

**Comment by mli0603** [comment]
Hi @dolcelee 

Can you:

- send me your config file and checkpoint?
- point me to which two commits you compared?

**Comment by dolcelee** [comment]
@mli0603 

- https://drive.google.com/file/d/1pafOO_sG9Fw-vNjFIxALPRntiULc0H8O/view?usp=sharing
- I uploaded my data and generated mesh
- This problem shows after the commit c91af8d5098c858df8e8dfa35fba8666d314782b

**Comment by deeepwin** [comment]
@mli0603 

I have also added my example to be able to reproduce:

- Checkpoint
- Config
- Data
- Mesh

https://1drv.ms/u/s!AtwBlzVMECHC4m1cGAxKqqd_mTKB?e=zVayUR

**Comment by deeepwin** [comment]
I have retried and it seems to work now (with commit b772282d26f62064401b1f4f0d53eefe908afdb3). I do not know why, but I did the following things:

1. I generated config file with:  `python3 projects/neuralangelo/scripts/generate_config.py --sequence_name mouse-2 --data_dir $DATA_PATH --scene_type object`, instead of using `custom/template.yaml`. 
2. I ensured that the bounding sphere is fitting tight around the object and updated the center point and scaling of sphere in the generated config file. After retraining, I could generate a decent mesh using `extract_mesh.py`

I have written a Notebook that you can find here that guides you through the process: [Notebook](https://github.com/deeepwin/nerf/blob/main/neurelangelo_data.ipynb)

**Comment by deeepwin** [comment]
@iam-machine Yes, sure, here my example, textured and without: 

![image](https://github.com/NVlabs/neuralangelo/assets/65670300/694e3db1-ed7d-4b1e-9256-bae316522c69)
![image](https://github.com/NVlabs/neuralangelo/assets/65670300/1dde8d46-87d5-45f1-b24a-f21535b9659a)

**Comment by mli0603** [comment]
Hi @deeepwin 

Thank you for sharing the useful info! We are looking into this issue. Will update!

**Comment by mli0603** [comment]
Hi @dolcelee 

On my end, even before the commit you provided, I am getting the same mesh results. I want to confirm that you are getting two different meshes with the same checkpoint. Is this the case?

**Comment by dolcelee** [comment]
@mli0603 

I retrained after the commit c91af8d5098c858df8e8dfa35fba8666d314782b since it need to be retrained. Therefore, it's not the same checkpoint which could generates good mesh. But the data and colmap processed files was same.

**Comment by dolcelee** [comment]
@mli0603 

I followed deepwin's method and did the whole process all over again, start at the colmap part. I don't know why but I do get a decent mesh! the shape of the mesh is pretty awesome, but the color is weird especially the skin part. Can you help me to improve the performance?
![_tmp_dingtalkgov_qt_pic_1694157581981](https://github.com/NVlabs/neuralangelo/assets/1515676/2136168a-5a60-4408-9f8f-e002466ad240)

**Comment by Dragonkingpan** [comment]
> @mli0603
> 
> I followed deepwin's method and did the whole process all over again, start at the colmap part. I don't know why but I do get a decent mesh! the shape of the mesh is pretty awesome, but the color is weird especially the skin part. Can you help me to improve the performance? ![_tmp_dingtalkgov_qt_pic_1694157581981](https://user-images.githubusercontent.com/1515676/266534953-2136168a-5a60-4408-9f8f-e002466ad240.jpg)
I also tested a custom model and just produced the third result. Mesh looks okay, but the color also clearly feels that the saturation is much higher than the original image.
![1694173555993](https://github.com/NVlabs/neuralangelo/assets/33677417/762163ea-6efb-47c5-b98d-d3de4c1f9664)
original image
![0018](https://github.com/NVlabs/neuralangelo/assets/33677417/c1343471-b73d-40d3-9920-2b80a3d48afa)

**Comment by Choco83** [comment]
> 2\. the bounding sphere is fitting tight around the object and updated the cen

@deeepwin thanks for nice notebook. Can you tell me how are you calculating camera poses for your video?

**Comment by deeepwin** [comment]
@Choco83 there are several ways. With the mouse-2 example I used Kiri, see NerfStudio description [here](https://docs.nerf.studio/en/latest/quickstart/custom_dataset.html). In one instance of data, I already had the poses in COLMAP format (images.txt) from the image sensor, see [here](https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses).

**Comment by zhj1013** [comment]
> > @mli0603
> > I followed deepwin's method and did the whole process all over again, start at the colmap part. I don't know why but I do get a decent mesh! the shape of the mesh is pretty awesome, but the color is weird especially the skin part. Can you help me to improve the performance? ![_tmp_dingtalkgov_qt_pic_1694157581981](https://user-images.githubusercontent.com/1515676/266534953-2136168a-5a60-4408-9f8f-e002466ad240.jpg)
> > I also tested a custom model and just produced the third result. Mesh looks okay, but the color also clearly feels that the saturation is much higher than the original image.
> > ![1694173555993](https://private-user-images.githubusercontent.com/33677417/266601844-762163ea-6efb-47c5-b98d-d3de4c1f9664.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTk0MDMsIm5iZiI6MTcwMTc1OTEwMywicGF0aCI6Ii8zMzY3NzQxNy8yNjY2MDE4NDQtNzYyMTYzZWEtNmVmYi00N2M1LWI5OGQtZDNkZTRjMWY5NjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA2NTE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZDMwNzFkMGRiMjliMTQyNjRiMzIyM2IxYjZmMDY3ZTJhZDI5ODU1NGM4ZWFjY2EwODM0NjhkM2FkMDI1OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m8VGnsu46ohVRNRsYFd099-EYxsQpmA8-tr3m-JkmsM)
> > original image
> > ![0018](https://private-user-images.githubusercontent.com/33677417/266602206-c1343471-b73d-40d3-9920-2b80a3d48afa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTk0MDMsIm5iZiI6MTcwMTc1OTEwMywicGF0aCI6Ii8zMzY3NzQxNy8yNjY2MDIyMDYtYzEzNDM0NzEtYjczZC00MGQzLTk5MjAtMmI4MGEzZDQ4YWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA2NTE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMjc5NDZiZDFjMjhlOTAzMDA3NGIyMzc2OGZjNmZmMWIxYzJkNzQ3ZGU4OTRmODg3MTUyMTMwNzIzYzQxNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.teWTQGbAX3k6E0ZBRkk3eWYtDAS-SoJmt-89c30fJkM)

Awesome result! Could you please tell me how your video was shot and whether the DATA preprocessing followed the DATA PROCESSING.md document ?
