### ISSUE TITLE
Does the picture mean my machine GPU not support?

### ISSUE THREAD

**Issue by xuduo18311199384** [NVlabs/neuralangelo#98]
![2023-09-01 14-31-16 的屏幕截图](https://github.com/NVlabs/neuralangelo/assets/30895764/58ad2f68-4d9c-4e41-8c8c-901c7a1fce5e)

**Comment by xuduo18311199384** [comment]
![2023-09-01 14-48-55 的屏幕截图](https://github.com/NVlabs/neuralangelo/assets/30895764/45f0e75a-9a8e-46fe-806b-e22846fc02bc)

**Comment by xuduo18311199384** [comment]
when docker run ...
![2023-09-01 14-57-06 的屏幕截图](https://github.com/NVlabs/neuralangelo/assets/30895764/335da60d-0601-4f5b-8355-334826c79f6a)

**Comment by chenhsuanlin** [comment]
Hi @xuduo18311199384, yes please upgrade your NVIDIA driver to 530.30+ to run the docker environment. Alternatively, you can follow instructions to install with conda.
